PLAYER_FILE = "./textures/wizard.png"
TILE_FILE = "./textures/world_tileset.png"


# HOUSE T1
H1_FULL_TILE = 9
H1_TOP_TILE = 1
H1_BOTTOM_TILE = 17
H1_LEFT_TILE = 8
H1_RIGHT_TILE = 10

H1_ITLCORNER_TILE = 0
H1_ITRCORNER_TILE = 2
H1_IBLCORNER_TILE = 16
H1_IBRCORNER_TILE = 18

H1_OTLCORNER_TILE = 19
H1_OTRCORNER_TILE = 20
H1_OBLCORNER_TILE = 27
H1_OBRCORNER_TILE = 28

H1_TILES = (
    H1_FULL_TILE, H1_TOP_TILE, H1_BOTTOM_TILE, H1_LEFT_TILE, H1_RIGHT_TILE,
    H1_ITLCORNER_TILE, H1_ITRCORNER_TILE, H1_IBLCORNER_TILE, H1_IBLCORNER_TILE,
    H1_OTLCORNER_TILE, H1_OTRCORNER_TILE, H1_OBLCORNER_TILE, H1_OBLCORNER_TILE,
)


# SANDS T1
SAND_FULL_TILE = 14
SAND_TOP_TILE = 6
SAND_BOTTOM_TILE = 22
SAND_LEFT_TILE = 13
SAND_RIGHT_TILE = 15

SAND_ITLCORNER_TILE = 5
SAND_ITRCORNER_TILE = 7
SAND_IBLCORNER_TILE = 21
SAND_IBLCORNER_TILE = 23

SAND_OTLCORNER_TILE = 5
SAND_OTRCORNER_TILE = 7
SAND_OBLCORNER_TILE = 13
SAND_OBLCORNER_TILE = 15

SAND_EMPTY_TILE = 29

SANDS_TILES = (
    SAND_FULL_TILE, SAND_TOP_TILE, SAND_BOTTOM_TILE, SAND_LEFT_TILE, SAND_RIGHT_TILE,
    SAND_ITLCORNER_TILE, SAND_ITRCORNER_TILE, SAND_IBLCORNER_TILE, SAND_IBLCORNER_TILE,
    SAND_OTLCORNER_TILE, SAND_OTRCORNER_TILE, SAND_OBLCORNER_TILE, SAND_OBLCORNER_TILE,
    SAND_EMPTY_TILE,
)


# OTHER
CACTUS_TILE = 30
ROCK_TILE = 31

BUSH1_TILE = 37
BUSH2_TILE = 38
BUSH3_TILE = 39
BUSH4_TILE = 46
BUSH5_TILE = 47

TABLE_TILE = 45

OBSTACLES_TILES = (
    CACTUS_TILE, ROCK_TILE, TABLE_TILE,
    BUSH1_TILE, BUSH2_TILE, BUSH3_TILE, BUSH4_TILE, BUSH5_TILE,
)
